﻿<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	  <PublishTrimmed>true</PublishTrimmed>
	  <TargetFramework>net8.0</TargetFramework>
	<PublishSingleFile>true</PublishSingleFile>
	<SelfContained>true</SelfContained>
    <ExcludeFilesFromDeployment>bin\**\*.pdb</ExcludeFilesFromDeployment>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<DebugSymbols>False</DebugSymbols>
		<DebugType>None</DebugType>
	</PropertyGroup>


</Project>
